version: '3.8'

services:
  frontend:
    container_name: interact-admin-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./frontend/.env

  backend:
    container_name: interact-admin-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5005:5005"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/logs:/app/logs/
    networks:
      - default
      - interact_go_backend-network

networks:
  interact_go_backend-network:
    external: true
